#
# Code Climate Quality configuration file
#
# Helps keep code and documentation clean.
#
# Advanced configuration reference:
#   https://docs.codeclimate.com/docs/advanced-configuration
#

version: 2

# Enable community plugins
plugins:
  bandit:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
  sonar-python:
    enabled: true
