# -*-mode:yml-*- vim:ft=yaml

# Config file for quality analysis at CodeClimate.com
#
# Helps keep code and documentation clean.
# See:
#   https://docs.codeclimate.com/docs/advanced-configuration
#   https://codeclimate.com/github/renemarc/countdoom

version: 2

# Enable community plugins
plugins:
  bandit:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
  sonar-python:
    enabled: true
