#
# Pre-commit configuration file
#   https://pre-commit.com/
#
# Additional information:
# - https://east.fm/posts/using-git-pre-commit-hooks/
#

fail_fast: false

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-added-large-files
        description: "Prevents giant files from being committed."
    -   id: check-ast
        description: "checks whether the files parse as valid python."
    -   id: check-byte-order-marker
        description: "Forbids files which have a UTF-8 byte-order marker."
    -   id: check-case-conflict
        description: "Checks for files that would conflict in case-insensitive filesystems."
    -   id: check-docstring-first
        description: "Checks a common error of defining a docstring after code."
    -   id: check-json
        description: "Checks json files for parsable syntax."
    -   id: check-merge-conflict
        description: "Check for files that contain merge conflict strings."
    -   id: check-yaml
        description: "Checks yaml files for parsable syntax."
    -   id: debug-statements
        description: "Check for debugger imports and py37+ `breakpoint()` calls in python source."
    -   id: end-of-file-fixer
        description: "Ensures that a file is either empty, or ends with one newline."
    -   id: fix-encoding-pragma
        description: "Adds # -*- coding: utf-8 -*- to the top of python files."
    -   id: mixed-line-ending
        description: "Replaces or checks mixed line ending."
        args: [--fix=lf]
    -   id: name-tests-test
        description: "Verifies that test files are named correctly."
        args: [--django]
    -   id: pretty-format-json
        description: "Sets a standard for formatting JSON files."
    -   id: requirements-txt-fixer
        description: "Sorts entries in requirements.txt."
    -   id: trailing-whitespace
        description: "Trims trailing whitespace."

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        language_version: python3
        require_serial: true
        types: [python]

-   repo: https://github.com/asottile/blacken-docs
    rev: v0.4.0
    hooks:
    -   id: blacken-docs
        description: "Runs `black` on python code blocks in documentation files."

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
        description: "Enforces style consistency across Python projects."

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.9
    hooks:
    -   id: isort
        description: "Sorts Python imports."

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check
        description: "Analyzes your Python requirements for known security vulnerabilities."

#-   repo: https://github.com/Lucas-C/pre-commit-hooks-markup
#    rev: v1.0.0
#    hooks:
#    -   id: rst-linter
#        description: "Checks .rst files with the same linter used by pypi.org."

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.2.0
    hooks:
    -   id: python-check-blanket-noqa
        description: "Enforces that `noqa` annotations always occur with specific codes."
    -   id: python-check-mock-methods
        description: "Prevents a common mistake of `assert mck.not_called()` or `assert mck.called_once_with(...)`."
    -   id: python-no-log-warn
        description: "Checks for the deprecated `.warn()` method of python loggers."
    -   id: rst-backticks
        description: "Detects common mistake of using single backticks when writing rst."

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.0
    hooks:
    -   id: git-dirty
        description: "Detects if git tree contains modified, staged, or untracked files."

#-   repo: https://gitlab.com/pycqa/bandit
#    rev: 1.5.1
#    hooks:
#    -   id: bandit

#-   repo: https://gitlab.com/pycqa/pydocstyle
#    rev: 2.0.0
#    hooks:
#    -   id: pydocstyle

#
#-   repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v2.3.0
#    hooks:
#    -   id: pylint

#-   repo: https://github.com/asottile/add-trailing-comma
#    rev: v0.7.1
#    hooks:
#    -   id: add-trailing-comma
