# -*-mode:yml-*- vim:ft=yaml

# Config file for documentation deployment on ReadTheDocs.org
#
# Compiles project repo documentation into web-accessible formats.
# See:
#   https://docs.readthedocs.io/en/stable/config-file/v2.html
#   https://countdoom.readthedocs.io/

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Formats of the documentation to be built.
formats: all

# Configure the Python environment to be used to build the doc.
python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
