# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Formats of the documentation to be built.
formats: all

# Configure the Python environment to be used to build the doc.
python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - requirements: requirements_dev.txt
