#
# Config file for automatic testing at travis-ci.org
#

dist: xenial
language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install --upgrade tox-travis --requirement requirements.txt --requirement requirements_dev.txt
    - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then travis_retry pip install black; fi

# Command to run tests, e.g. python setup.py test
script:
    - pylint ./countdoom/ ./tests/*.py
    - if [[ $TRAVIS_PYTHON_VERSION != '3.8' ]]; then (flake8 .); fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then (black --check --diff .); fi
    - tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: renemarc
#  password:
#    secure: PLEASE_REPLACE_ME
#  on:
#    tags: true
#    repo: renemarc/countdoom
#    python: 3.6
