# -*-mode:yml-*- vim:ft=yaml

# Config file for automatic testing at Travis-CI.com
#
# Once tests are performed sucessfully, a coverage report is sent out to
# CodeClimate.com and a completion signal is sent to CodeCov.io.
# See https://docs.codeclimate.com/docs/travis-ci-test-coverage

# Setup environment for Python builds.
dist: xenial
language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  # Disabled until typed_ast (used by pylint) is fixed.
  # See https://github.com/python/typed_ast/issues/134
  # - "pypy3"

# Declare required variables for Code Climate
env:
  global:
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
    - CC_TEST_REPORTER_ID=eb5a902253f7a3dfa19e6c4507825f5911142de119b037a27d276510845ed588

# Download Code Climate test reporter.
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

# Warn Code Climate that a test is about to run.
before_script:
  - ./cc-test-reporter before-build

# Install dependencies.
install:
  - pip install --upgrade tox-travis
  - pip install .[lint]
  - pip install .[test]

# Run tests.
script:
  - pylint ./countdoom/ ./tests/*.py
  - if [[ $TRAVIS_PYTHON_VERSION != '3.8' ]]; then (flake8 .); fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then (black --check --diff .); fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then (coverage run --source countdoom --module pytest; coverage xml); fi
  - tox

# Submit test results to Code Climate and CodeCov.
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then ./cc-test-reporter format-coverage --input-type coverage.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then ./cc-test-reporter upload-coverage; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then codecov; fi

# Build Python wheel and submit it to PyPI when new tags are pushed.
#
# PyPI's token must be encrypted with Travis-CI CLi tool:
# $ travis encrypt YOUR_TOKEN_PASSWORD --com --add deploy.password
deploy:
 provider: pypi
 distributions: sdist bdist_wheel
 user: renemarc
 password:
   secure: VC4YuPjvJorYWxjHRfAw5TfdA74XpRE4MkANwFNP3Lx2gU0+6wKP7lBtJNfx5KJtoBd77qMYOOIsNkUv5AY9O1taXv/C5ZHIQdLPFnqk6G1+N5n0pHhSEMhFro/70uMCxBJw15GsYdRnUZ6WbNiqk3VeBlL9DpO3CT32ftqDqePtQ0B3A0AU3pHi3B7AW91YTFFgbZj6sec0sY3WQ+gW9oQLp8CrPRghbZDRBIskgPSGoImoXMD+2EzRcYeG7A0gF36uzp6j+8X+CYQoYtKUOzxzOxLxiOPz6DKjvtId+PxpxWXfbFVg17n8DpCpVQa72RDBJzKCTFMfDueUiq+B3SypzLHBrmKZusJhDUlfR7bxxfiahKJPwgDGreY1YgzXYsLwjNxY/0SGqkvPJuUA5+pHf2pU5YQJilPpXGesj7Tgy4tbbPBzOtO2fp7LB75glHFGZuqiPZRS+hTbZnoiJPTgjGHI64c3nE2aT/UMe1Jve1jFlsPYCaksmMUThsach5ml4lUpn9lhBE7omSOMf1MolU8LBTcODxPBNySq7HeAJDO+RgAwOi9nEjaiqRVkjCOLxjafuuUlkHye9lLdbtWc5uH5eOSdCovTv+CWWK9+HWfnrR4jgwvHzZOAyRb7AJm3hxpTNFMEvkKVWh1a0gacw3Q3NXp+LwhpZg5/QEc=
 on:
   tags: true
   repo: renemarc/countdoom
   python: "3.6"
