[tool.black]
line-length = 79
skip-string-normalization = true
target_version = ['cpy35']
include = '\.pyi?$'
# exclude a few common directories in the root of the project.
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | venv
  )/
)
'''

#[tool.isort]
#multi_line_output = 3
#include_trailing_comma = true
#force_grid_wrap = 0
#combine_as_imports = true
#line_length = 79
